# Generated by Django 4.0.3 on 2022-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_no',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
