# Generated by Django 4.0.3 on 2022-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_aadhar_aadhar_no_alter_bank_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_detail',
            name='address',
            field=models.ManyToManyField(related_name='pd_address', to='api.address'),
        ),
    ]
